// UserContext.js
import React, { createContext, useState } from "react";

const UserContext = createContext();

const userDetailsData = {
  1: {
    name: "Alice Smith",
    username: "alice",
    email: "alice@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
  },
  2: {
    name: "Bob Johnson",
    username: "bob",
    email: "bob@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
  },
  3: {
    name: "Charlie Brown",
    username: "charlie",
    email: "charlie@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
  },
  4: {
    name: "Diana Prince",
    username: "diana",
    email: "diana@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    isPhoneVerified: false,
    isEmailVerified: true,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
  },
  5: {
    name: "Eve Adams",
    username: "eve",
    email: "eve@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",

    isPhoneVerified: false,
    isEmailVerified: true,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
  },
  // 6: {
  //   name: "Frank Miller",
  //   username: "frank",
  //   email: "frank@gmail.com",
  //   status: "Active",
  //   isVerified: false,
  //   country: "United States of America",
  //   state: "state",
  //   city: "city",
  //   isPhoneVerified: false,
  //   isEmailVerified: true,
  //   bio: "",
  //   availableCoin: 0,
  //   lastActive: "04/06/2024 10:35 AM",
  //   createdDate: "04/06/2024 10:35 AM",
  //   image: "",
  //   loginMode: "social",
  //   deviceType: "iOS",
  //   deviceModel: "Rosemary’s iPhone",
  //   loggedAt: "04/06/2024 10:35 AM",
  //   loginIp: "64.44.177.36",
  // },
  // 7: {
  //   name: "Grace Lee",
  //   username: "grace",
  //   email: "grace@gmail.com",
  //   status: "Active",
  //   isVerified: false,
  //   country: "United States of America",
  //   state: "state",
  //   city: "city",
  //   isPhoneVerified: false,
  //   isEmailVerified: true,
  //   bio: "",
  //   availableCoin: 0,
  //   lastActive: "04/06/2024 10:35 AM",
  //   createdDate: "04/06/2024 10:35 AM",
  //   image: "",
  //   loginMode: "social",
  //   deviceType: "iOS",
  //   deviceModel: "Rosemary’s iPhone",
  //   loggedAt: "04/06/2024 10:35 AM",
  //   loginIp: "64.44.177.36",
  // },
  // 8: {
  //   name: "Hank Hill",
  //   username: "hank",
  //   email: "hank@gmail.com",
  //   status: "Active",
  //   isVerified: false,
  //   country: "United States of America",
  //   state: "state",
  //   city: "city",
  //   isPhoneVerified: false,
  //   isEmailVerified: true,
  //   bio: "",
  //   availableCoin: 0,
  //   lastActive: "04/06/2024 10:35 AM",
  //   createdDate: "04/06/2024 10:35 AM",
  //   image: "",
  //   loginMode: "social",
  //   deviceType: "iOS",
  //   deviceModel: "Rosemary’s iPhone",
  //   loggedAt: "04/06/2024 10:35 AM",
  //   loginIp: "64.44.177.36",
  // },
  // 9: {
  //   name: "Ivy Green",
  //   username: "ivy",
  //   email: "ivy@gmail.com",
  //   status: "Active",
  //   isVerified: false,
  //   country: "United States of America",
  //   state: "state",
  //   city: "city",
  //   isPhoneVerified: false,
  //   isEmailVerified: true,
  //   bio: "",
  //   availableCoin: 0,
  //   lastActive: "04/06/2024 10:35 AM",
  //   createdDate: "04/06/2024 10:35 AM",
  //   image: "",
  //   loginMode: "social",
  //   deviceType: "iOS",
  //   deviceModel: "Rosemary’s iPhone",
  //   loggedAt: "04/06/2024 10:35 AM",
  //   loginIp: "64.44.177.36",
  // },
  // 10: {
  //   name: "Jack White",
  //   username: "jack",
  //   email: "jack@gmail.com",
  //   status: "Active",
  //   isVerified: false,
  //   country: "United States of America",
  //   state: "state",
  //   city: "city",
  //   isPhoneVerified: false,
  //   isEmailVerified: true,
  //   bio: "",
  //   availableCoin: 0,
  //   lastActive: "04/06/2024 10:35 AM",
  //   createdDate: "04/06/2024 10:35 AM",
  //   image: "",
  //   // loginMode: "social",
  //   // deviceType: "iOS",
  //   // deviceModel: "Rosemary’s iPhone",
  //   // loggedAt: "04/06/2024 10:35 AM",
  //   // loginIp: "64.44.177.36",
  // },
};

const UserProvider = ({ children }) => {
  const [users, setUsers] = useState(userDetailsData);

  return (
    <UserContext.Provider value={{ users, setUsers }}>
      {children}
    </UserContext.Provider>
  );
};

export { UserContext, UserProvider };
