import React, { createContext, useState, useContext } from "react";

const UserContext = createContext();

const userDetailsData = {
  1: {
    name: "Alice Smith",
    username: "alice",
    email: "alice@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
    posts: [
      {
        id: 1,
        title: "sample post",
        totalViews: 1,
        totalLikes: 2,
        popularPoints: 3,
        totalComments: 4,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
      {
        id: 2,
        title: "sample post",
        totalViews: 10,
        totalLikes: 20,
        popularPoints: 30,
        totalComments: 40,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
      {
        id: 3,
        title: "sample post",
        totalViews: 11,
        totalLikes: 21,
        popularPoints: 31,
        totalComments: 41,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
    ],
    viewFollowing: ["bob", "charlie"],
    viewFollowers: ["diana", "eve"],
    blockedUsers: ["charlie"],
    stories: [
      {
        id: 1,
        type: "Image",
        description: "Alice's first story",
        backgroundColor: "#FFFFFF",
        thumbnail: "path/to/thumbnail1.png",
        video: "path/to/video1.mp4",
        status: "Expired",
      },
    ],
    userLive: [
      {
        id: 1,
        startTime: "10:00 AM",
        endTime: "11:00 AM",
        totalTime: "1 hour",
        action: "",
      },
    ],
    userReels: [
      {
        id: 1,
        title: "Sample Reel 1",
        totalViews: 100,
        totalLikes: 50,
        totalComments: 10,
        totalShares: 5,
        status: "Active",
        action: "View",
      },
      {
        id: 2,
        title: "Sample Reel 1",
        totalViews: 100,
        totalLikes: 50,
        totalComments: 10,
        totalShares: 5,
        status: "Active",
        action: "View",
      },
      // Add more reels as needed
    ],
  },
  2: {
    name: "Bob Johnson",
    username: "bob",
    email: "bob@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
    posts: [
      {
        id: 2,
        title: "sample post",
        totalViews: 10,
        totalLikes: 11,
        popularPoints: 12,
        totalComments: 13,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
    ],
    viewFollowing: [],
    viewFollowers: ["alice"],
    blockedUsers: ["charlie"],
    stories: [
      {
        id: 2,
        type: "Image",
        description: "Bob's first story",
        backgroundColor: "#FFFFFF",
        thumbnail: "path/to/thumbnail1.png",
        video: "path/to/video1.mp4",
        status: "Active",
      },
    ],
    userLive: [
      {
        id: 2,
        startTime: "09:00 AM",
        endTime: "10:30 AM",
        totalTime: "1.5 hours",
        action: "",
      },
    ],
    userReels: [
      {
        id: 1,
        title: "Sample Reel 1",
        totalViews: 100,
        totalLikes: 50,
        totalComments: 10,
        totalShares: 5,
        status: "Active",
        action: "View",
      },
      {
        id: 2,
        title: "Sample Reel 2",
        totalViews: 100,
        totalLikes: 50,
        totalComments: 10,
        totalShares: 5,
        status: "Active",
        action: "View",
      },
      // Add more reels as needed
    ],
  },
  3: {
    name: "Charlie Brown",
    username: "charlie",
    email: "charlie@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
    posts: [
      {
        id: 3,
        title: "sample post",
        totalViews: 19,
        totalLikes: 2,
        popularPoints: 23,
        totalComments: 3,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
    ],
    viewFollowing: ["alice"],
    viewFollowers: ["diana"],
    blockedUsers: ["alice"],
    stories: [],
    userLive: [
      {
        id: 3,
        startTime: "10:00 AM",
        endTime: "11:00 AM",
        totalTime: "1 hour",
        action: "",
      },
    ],
    userReels: [
      {
        id: 1,
        title: "Sample Reel 1",
        totalViews: 100,
        totalLikes: 50,
        totalComments: 10,
        totalShares: 5,
        status: "Active",
        action: "View",
      },

      // Add more reels as needed
    ],
  },
  4: {
    name: "Diana Prince",
    username: "diana",
    email: "diana@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
    posts: [
      {
        id: 1,
        title: "sample post",
        totalViews: 1,
        totalLikes: 2,
        popularPoints: 3,
        totalComments: 4,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
    ],
    viewFollowing: [],
    viewFollowers: ["alice"],
    blockedUsers: ["charlie"],
    stories: [],
    userLive: [
      {
        id: 4,
        startTime: "17:00 PM",
        endTime: "18:00 PM",
        totalTime: "1 hour",
        action: "",
      },
    ],
    userReels: [],
  },
  5: {
    name: "Eve Adams",
    username: "eve",
    email: "eve@gmail.com",
    status: "Active",
    isVerified: false,
    country: "United States of America",
    state: "state",
    city: "city",
    phoneNumber: 12334567,
    bio: "",
    availableCoin: 0,
    lastActive: "04/06/2024 10:35 AM",
    createdDate: "04/06/2024 10:35 AM",
    image: "",
    loginMode: "social",
    deviceType: "iOS",
    deviceModel: "Rosemary’s iPhone",
    loggedAt: "04/06/2024 10:35 AM",
    loginIp: "64.44.177.36",
    posts: [
      {
        id: 1,
        title: "sample post",
        totalViews: 1,
        totalLikes: 2,
        popularPoints: 3,
        totalComments: 4,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
      {
        id: 2,
        title: "sample post",
        totalViews: 1,
        totalLikes: 2,
        popularPoints: 3,
        totalComments: 4,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
      {
        id: 3,
        title: "sample post",
        totalViews: 100,
        totalLikes: 200,
        popularPoints: 300,
        totalComments: 400,
        status: "Active",
        createdAt: "09/06/2024 9:44 AM",
      },
    ],
    viewFollowing: [],
    viewFollowers: ["alice", "bob"],
    blockedUsers: ["charlie"],
    stories: [
      {
        id: 5,
        type: "Image",
        description: "Eve's first story",
        backgroundColor: "",
        thumbnail: "path/to/thumbnail1.png",
        video: "path/to/video1.mp4",
        status: "Active",
      },
    ],
    userLive: [],
    userReels: [
      {
        id: 1,
        title: " Reel 1",
        totalViews: 300,
        totalLikes: 20,
        totalComments: 20,
        totalShares: 12,
        status: "Active",
        action: "View",
      },
    ],
  },
};

const UserProvider = ({ children }) => {
  const [users, setUsers] = useState(userDetailsData);

  return (
    <UserContext.Provider value={{ users, setUsers }}>
      {children}
    </UserContext.Provider>
  );
};

// Custom hook to use the UserContext
const useUserContext = () => {
  const context = useContext(UserContext);
  if (!context) {
    throw new Error("useUserContext must be used within a UserProvider");
  }
  return context;
};

export { UserContext, UserProvider, useUserContext };
